export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    me: '/auth/me',
    sendOtp: '/auth/send-otp',
    verifyOtp: '/auth/verify-otp',
    resendOtp: '/auth/resend-otp',
    forgotPasswordSendOtp: '/auth/forgot-password/send-otp',
    forgotPasswordVerifyOtp: '/auth/forgot-password/verify-otp',
    forgotPasswordReset: '/auth/forgot-password/reset',
    logout: '/auth/logout',
  },
  admin: {
    users: '/admin/users',
    blockUser: (id: string) => `/admin/users/${id}/block`,
    unblockUser: (id: string) => `/admin/users/${id}/unblock`,
    createAdmin: '/admin/create-admin',
    makeAdmin: (id: string) => `/admin/users/${id}/make-admin`,
    removeAdmin: (id: string) => `/admin/users/${id}/remove-admin`,
    grids: '/admin/grids',
    grid: (id: string) => `/admin/grids/${id}`,
    openGrid: (id: string) => `/admin/grids/${id}/open`,
    closeGrid: (id: string) => `/admin/grids/${id}/close`,
    setWinningNumber: (id: string) => `/admin/grids/${id}/winning-number`,
    userHistory: (id: number | string) => `/admin/users/${id}/history`,
    payments: '/admin/payments',
    paymentUpdate: (id: number | string) => `/admin/payments/${id}`,
  },
  grid: {
    active: '/grid/active',
    numbers: (gridId: string) => `/grid/${gridId}/numbers`,
    subTickets: (gridId: string, number: number) => `/grid/${gridId}/numbers/${number}/subtickets`,
    buy: (gridId: string) => `/grid/${gridId}/buy`,
  },
  draws: {
    active: '/grid/active',
    list: '/admin/grids',
    close: (id: number | string) => `/admin/grids/${id}/close`,
  },
  tickets: {
    create: '/tickets',
    mine: '/tickets/me',
    update: (id: number | string) => `/admin/tickets/${id}`,
  },
  payments: {
    list: '/payments',
    create: '/payments',
    slip: (id: number | string) => `/payments/${id}/slip`,
  },
}
